### ISSUE TITLE
Database XML mistakes

### ISSUE THREAD

**Issue by mariomadproductions** [Ptrk25/GroovyFX#1]
It lists physical demos as "special demos"

**Comment by Ptrk25** [comment]
you mean the special demos that are listed as "eShopApp"?

**Comment by mariomadproductions** [comment]
Yes. They have the same IDs as the cart demos. How are they even downloadable from the NUS?

**Comment by Ptrk25** [comment]
Can you please give me an example, so that I can look up?

**Comment by mariomadproductions** [comment]
search "mario kart"
